#remote_theme: aspirethemes/type
remote_theme: sharu725/hagura

# --- Required options --- #

# Name of website
title: Morbergs receptsamling

# Your name to show in the footer
author: Niklas Morberg

# --- Remove double titles fram pages
plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
