remote_theme: daattali/beautiful-jekyll

# --- Required options --- #

# Name of website
title: Morbergs receptsamling

# Your name to show in the footer
author: Niklas Morberg

# --- test to remove double titles fram pages

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
