name: Update table of contents

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update table of contents (index.md)
      run: |
        make jekyll
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic update of index.md
